name: Experiment Docker meta GitHub Action

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # The docker tag "latest" is only generated in certain conditions by
          # default. The below setup forces that the use of "latest" tag for any
          # new image generated. You can find more about it in the below ref.
          # Ref: https://github.com/docker/metadata-action?tab=readme-ov-file#latest-tag
          flavor: |
            latest=true
          images: |
            rytswd/docker-lab/meta
            rytswd-docker-lab-meta
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}
            type=ref,event=branch
            type=ref,event=pr
            type=edge
            type=sha
