name: Experiment Docker meta GitHub Action

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            rytswd/docker-lab/meta
            rytswd-docker-lab-meta
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss'}}
            type=ref,event=branch
            type=ref,event=pr
            type=edge
            type=sha
